const english = {
        home:"home",
        pricing:"pricing",
        texttospeech:"Text to speech",
        account:"Account",
        landingpagetitle:"Next-Generation AI Voice Generation",
        langingpagep:" Turn any text into natural, professional-grade audio instantly. Choose from dozens of hyper-realistic voices across multiple languages, type your script, and download your audio in seconds.",
        langingpagefirstbtn:"Text to speech",
        login:"login",
        signup:"Signup",
        signout:"signout",
        emailverificationnotice:"Please verify your email address to unlock all features.",
        emailverificationlink:"Resend Verification Link",
        langinagepagesecondbtn:"Pricing",
        langinepagepresentationtitle:"How It Works in 2 Simple Steps",
        langinepagefirstcardtitle:"Input Text & Select a Voice",
        langinepagefirstcardp:"Type or paste your script into our editor. Choose from our diverse library of hyper-realistic, multilingual AI voices and adjust the tone to perfectly match your project.",
        landingpageprompt:`"مع هدرلي رجّع أي كتيبة لأوديو احترافي في رمشة عين. خيّر الصوت لي يعجبك، أكتب واش راك حاب، وخلّي الذكاء الاصطناعي يدير خدمتوا"`,
        landingpagesecondcardtitle:"Generate & Download",
        landingpagesecondcardp:"Click generate and let our advanced AI engine process your text in seconds. Preview the audio stream instantly, then download your studio-quality MP3 file ready for use.",
        landingpagequote:"We started this project with one simple goal: to remove the friction between a great script and professional audio. Your words deserve to be heard, and you shouldn't need a recording studio to make that happen.",
        landingepagequoter:"eHdrli ceo",
        privacy:"privacy",
        terms:"terms",
        rights:"© 2026 eHdrli. All rights reserved.",
        /* pricing */
        pricingtitle:"Simple pricing that scales with your needs",
        pricingp:"Start generating lifelike audio immediately and upgrade only when you need more power. We believe in straightforward, transparent pricing with no hidden fees—just choose the character limit that fits your monthly production, whether you are a solo creator or a growing business.",
        pricingfirstcard:"Essential voices and limits for your daily audio needs",
        pricingsecondcard:"Maximum limits and priority generation for heavy users.",
        pricingadvantageone:"Text To Speech Access",
        pricingadvantagetwo:"Ai Franco-darija to Arabic-darija",
        pricingadvantagethree:"Characters",
        pricingfirstbutton:"Get Started",
        pricingsecondbutton:"Join Now",
        questiontitle:"Common Questions",
        questionfirsttitle:"Can I get more characters if I run out before the month ends?",
        questionfirstp:"Yes! If you run low on credits, you don't have to wait for your next billing cycle. You can simply purchase another plan at any time. Thanks to our credit-stacking system, your new characters are added instantly, and you will never lose any unused characters from your previous plan until their original expiration date.",
        questionsecondtitle:"Whenever people buy AI voice generation, their #1 concern is whether they will get copyright strikes on YouTube or if they can use it for client work?",
        questionsecondp:"Absolutely. Any audio you generate and download using our Plus or Pro plans is fully cleared for commercial use. You can monetize the voices on YouTube, use them in podcasts, video games, advertisements, or client projects without paying any extra royalties.",
        /* text to speech */
        balance:"balance",
        chars:"chars",
        whattosay:"What should they say ?",
        isscript:"Is script in latin darija ?",
        typescript:"Type or paste your script here.",
        characters:"characters",
        scriptbutton:"Generate Speech",
        selectvoices:"Select Voices",        
        download:"تحميل",
        /* login */
        logintitle:"Create your account join us today and start transforming your text into studio-quality voiceovers.",
        fullname:"Full Name",
        email:"Email address",
        password:"Password",
        forgotpassword:"Forgot password ?",
        signinbtn:"Sign in",
        continuewith:"OR CONTINUE WITH",
        noaccount:"Don't have an account ? ",
        signup:"Sign up",
        agree:"By authenticating, you agree to our ",
        terms:"Terms",
        and:"and",
        privacy:"Privacy Policy",
        /* sign up */
        signuptitle:"Create your account join us today and start transforming your text into studio-quality voiceovers.",
        alreadyregistered:"Already registered ?",
        /* forgot password */
        forgotpasswordtitle:"Forgot your password ?",
        forgotpasswordp:"Enter your email address and we'll send you a link to reset your password.",
        resetlink:"Send reset Link",
        back:"Back to Sign in",
        /* reset passwrd */
        resetpasswordtitle:"Create New Password",
        newpassword:"New Password",
        confirmnewpassword:"Confirm New Password",
        setnewpassword:"Set New Password",
        /* account */
        hello:"Hello,",
        accounttitle:"Manage your sanctuary settings.",
        account:"Account",
        edit:"Edit",
        save:"Save",
        cancel:"Cancel",
        changepassword:"Change Password",
        subscriptions:"Subscriptions",
        active:"Active",
        charactersused:"Characters used",
        end:"Ends in",
        
        

        


        

}
export default english;